id: P000805
initial_creation_type: ocr
created_at: 1/04/2021
last_modified_at: 2021-12-17 10:11:33.368646
source_metadata:
  id: bdr:W1GS105195
  title: ཐོབ་ཡིག་བུམ་པ་བཟང་པོ
  volumes:
    8ff76a263ea14bb5beec747060b5699d:
      image_group_id: I1PD36271
      title: ''
      base_file: v001.txt
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
