id: opecha:P000805
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS105195
  title: ཐོབ་ཡིག་བུམ་པ་བཟང་པོ
  volumes:
    8ff76a263ea14bb5beec747060b5699d:
      image_group_id: I1PD36271
      title: ''
      base_file: v001.txt
  author: ''
